#!/usr/bin/python3
import time
from sys import exit
from roboclaw_3 import Roboclaw

# set up raspberry pi
import RPi.GPIO as gpio
gpio.setmode(gpio.BCM)
HALLPIN = 2
gpio.setup(HALLPIN, gpio.IN)

# constants
CLAW_FORWARDROT = 60
CLAW_BACKWARDROT = 240
ELBOW_FULLROT = 3250
WRIST_FULLROT = 1000
BASE_FULLROT = 15000
FULLROT = 360

ROBOCLAW_1 = 128
ROBOCLAW_2 = 129


while (True):
    if(gpio.input(HALLPIN) == True):
        print("magnet detected")
    else:
        print(" ")

if __name__ == "__main__":
