controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - base_joint
      - elbow_joint
      - wrist_joint
      # - rollmotor

# rat_arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - base_joint
#     - elbow_joint
#     - wrist_joint
#   gains:
#     base_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1